# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-Latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'FSharp.ProjectScaffold.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FSharp.ProjectScaffold.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'FSharp.ProjectScaffold.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true